{{- $global_data := .Values.global }}
{{- $graphinstaller_data := $global_data.graphinstaller.graphinstaller }}
{{- $graphinstaller_config := $graphinstaller_data.config }}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "graphinstaller.fullname" . }}
  labels:
    {{- include "graphinstaller.labels" . | nindent 4 }}
spec:
  {{- if not $graphinstaller_data.autoscaling.enabled }}
  replicas: {{ $graphinstaller_data.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "graphinstaller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "graphinstaller.labels" . | nindent 8 }}
        {{- with $graphinstaller_data.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.global.imagePullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
      {{- end }}
      initContainers:

        - name: init-wait-resolve-pgbouncer
          image: {{ .Values.global.imageInit.repository }}:{{ .Values.global.imageInit.tag }}
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          args:
            - "-c"
            - |
              until IP=$(nslookup ${DB_HOST} 2>/dev/null | grep "Address: " | sed 's/.*: //g;s/ .*//g'); [ -n "$IP" ]; do
                echo "Waiting for PgBouncer IP resolution";
                sleep 2;
              done
          env:
            - name: DB_HOST
              value: {{ $graphinstaller_config.postgres.host | quote }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

        - name: init-wait-pgbouncer-port
          image: {{ .Values.global.imageInit.repository }}:{{ .Values.global.imageInit.tag }}
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          args:
            - "-c"
            - |
              until nc -zw1 ${DB_HOST} ${DB_PORT}; do
                echo "Waiting for PgBouncer port";
                sleep 2;
              done
          env:
            - name: DB_HOST
              value: {{ $graphinstaller_config.postgres.host | quote }}
            - name: DB_PORT
              value: {{ $graphinstaller_config.postgres.port | quote }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

      serviceAccountName: {{ include "graphinstaller.serviceAccountName" . }}
      securityContext:
        {{- toYaml $graphinstaller_data.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml $graphinstaller_data.securityContext | nindent 12 }}
          image: "{{ $graphinstaller_data.image.repository }}:{{ $graphinstaller_data.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $graphinstaller_data.image.pullPolicy }}
          command: ["/graph-installer/graph-installer"]
          args: ["--config=/graph-installer/{{ $graphinstaller_data.config_file }}", "--install=/graph-installer/{{ $graphinstaller_data.installs_file }}"]
          env:
            - name: INTERNAL_HOST
              value: "{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local"
          ports:
            - name: apiserver
              containerPort: {{ $graphinstaller_data.config.api_server.listen_port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ $graphinstaller_data.config.metrics.listen_port }}
              protocol: TCP
          resources:
            {{- toYaml $graphinstaller_data.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /graph-installer/{{ $graphinstaller_data.config_file }}
              subPath: {{ $graphinstaller_data.config_file }}
            - name: installs
              mountPath: /graph-installer/{{ $graphinstaller_data.installs_file }}
              subPath: {{ $graphinstaller_data.installs_file }}
      volumes:
        - name: config
          configMap:
            name: {{ include "graphinstaller.fullname" . }}
        - name: installs
          configMap:
            name: {{ include "graphinstaller.fullname" . }}-installs
      {{- with $graphinstaller_data.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $graphinstaller_data.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $graphinstaller_data.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
