apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphinstaller.fullname" . }}
  labels:
    {{- include "graphinstaller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.global.graphinstaller.graphinstaller.service.type }}
  ports:
    - port: {{ .Values.global.graphinstaller.graphinstaller.service.port }}
      targetPort: apiserver
      protocol: TCP
      name: apiserver
    - port: {{ .Values.global.graphinstaller.graphinstaller.config.metrics.listen_port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "graphinstaller.selectorLabels" . | nindent 4 }}
